database:
  TIMESCALEDB_USER: "{{ env_var('DISKTEST_TIMESCALEDB_USER')}}"
  TIMESCALEDB_PASSWORD: "{{ env_var('DISKTEST_TIMESCALEDB_PASSWORD')}}"
  TIMESCALEDB_DATABASE: "{{ env_var('DISKTEST_TIMESCALEDB_DATABASE')}}"
  TIMESCALEDB_HOST: "{{ env_var('DISKTEST_TIMESCALEDB_HOST')}}"
  TIMESCALEDB_PORT: "{{ env_var('DISKTEST_TIMESCALEDB_PORT')}}"
  TIMESCALEDB_SCHEMA: "{{ env_var('DISKTEST_TIMESCALEDB_SCHEMA')}}"

general:
  log_file: "./logs/disktest_timescaledb_logs.log"