database:
  INFLUXDB_USERNAME: "{{ env_var('READBENCH_INFLUXDB_USERNAME')}}"
  INFLUXDB_PASSWORD: "{{ env_var('READBENCH_INFLUXDB_PASSWORD')}}"
  INFLUXDB_ORG: "{{ env_var('READBENCH_INFLUXDB_ORG')}}"
  INFLUXDB_BUCKET: "{{ env_var('READBENCH_INFLUXDB_BUCKET')}}"
  INFLUXDB_HOST: "{{ env_var('READBENCH_INFLUXDB_HOST')}}"
  INFLUXDB_PORT: "{{ env_var('READBENCH_INFLUXDB_PORT')}}"
  INFLUXDB_TOKEN: "{{ env_var('READBENCH_INFLUXDB_TOKEN')}}"

general:
  log_file: "./logs/readbench_influxdb_logs.log"